# Generated by Django 4.1 on 2022-10-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0002_alter_image_mean_text_alter_image_og_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='mean_text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='og_text',
        ),
    ]
