# Generated by Django 4.1 on 2022-10-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0003_remove_image_mean_text_remove_image_og_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Img2txt',
        ),
    ]
