# Generated by Django 4.1 on 2022-12-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0004_rename_image_img2txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25)),
                ('c_code', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Translang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25)),
                ('c_code', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='img2txt',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
